### ISSUE TITLE
Understanding HCS running hash in Java [ hbar 1500 ]

### ISSUE THREAD

**Issue by topshef** [topshef/tips-for-tasks#1]
Task:
- demo in Java how to get from the running hash of one message to the running hash of the next. 
- perform a test using [sample data](https://hbar.live/mirror/hcs/?topicId=0.0.43738&fromSeq=5801&sortBy=asc&limit=2&unpack=hex&mirrornode=dragonglass&outputformat=debug), and demo that the calculated running hash = actual running hash
- hard-coding the test values is ok

Delivery is java code that accomplishes the above, and either a demo or assistance in running it with Eclipse

repo with base java code: https://github.com/topshef/hash/blob/master/hcsRunningHash.java

something similar to this, but in java with result PASS! https://kpay.live/hash/hcsRunningHash.php

Thanks !

**Comment by topshef** [comment]
Purpose: learning exercise in prep for appnet verification designs

**Comment by topshef** [comment]
assigned https://github.com/rahul-kothari

**Comment by rahul-kothari** [comment]
Created [HCSRunningHashDemo.java](https://github.com/topshef/tips-for-tasks/blob/main/HCSRunningHashDemo.java)

Instructions to run:
1. Download the [file](https://raw.githubusercontent.com/topshef/tips-for-tasks/main/HCSRunningHashDemo.java).

2a. In an IDE* (VSCode/Eclipse, IntelliJ), open the file and run the `main()` method
2b. In a terminal:
    i. cd into the directory
    ii.
```
javac HCSRunningHashDemo.java
java HCSRunningHashDemo
```

Change parameters between line 15-30 to have a play around with different values.

 `*` To run in Windows without an IDE download this [bat](https://raw.githubusercontent.com/topshef/tips-for-tasks/main/HCSRunningHashDemo.bat) file

**Comment by topshef** [comment]
Here is a video demo of the above: https://1drv.ms/v/s!AvLsQBfHUrt9jfh3A_8Kl_PmmpglqQ
10 mins, includes demo of kabuto raw tx lookup. sorry no option to speed up playback!

Assumes no knowledge of Java and does not require an IDE, only need Java JDK https://www.oracle.com/java/technologies/javase-jdk13-downloads.html

**Comment by topshef** [comment]
Raw tx can also been seen on Dragonglass, eg https://app.dragonglass.me/hedera/transactions/00274981601935168799000000

Also via raw api: https://api.dragonglass.me/hedera/api/transactions/raw/
They also plan to include nanos in a future release of the summary apis

**Comment by topshef** [comment]
Greg: Note that the transaction hash is now provided by the v2 SDKs, there are braking changes with v2, so proceed accordingly.
https://discord.com/channels/373889138199494658/535491106348072970/765201179088519168
